services:
  eduplanner:
    image: eduplanner
    container_name: eduplanner-app
    restart: no
    ports:
      - "8081:8080"
    build:
      context: .
      dockerfile: ./src/EduPlanner.API/Dockerfile
    networks:
      - edunetwork
  eduplanner-mariadb:
    image: mariadb:latest
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: atsNew
    ports:
      - "3306:3306"
    networks:
      - edunetwork
    volumes:
      - mariadb-data:/var/lib/mariadb/data

volumes:
  mariadb-data:
    driver: local
    
networks:
  edunetwork:
    driver: bridge
